{
 "title": "HAProxy 2 Full",
 "description": "HAProxy with Prometheus data",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "host", "label": "Host", "query": { "query": "label_values(haproxy_up{},pod)" } },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_bytes_in_total{pod=~\"$host\"},backend)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_bytes_in_total{pod=~\"$host\"},frontend)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_bytes_in_total{pod=~\"$host\"}, exported_pod)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{}, code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Basic General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All HTTP responses rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "- back / + front" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_responses_total{frontend=~\"$frontend\",code=~\"$code\",pod=~\"$host\"}[$__rate_interval])) by (code)",
     "legendFormat": "Frontend: [ {{code}} ] ({{pod}}) {{frontend}} "
    },
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{backend=~\"$backend\",code=~\"$code\",pod=~\"$host\"}[$__rate_interval])) by (code)",
     "legendFormat": "Backend: [ {{code}} ] ({{pod}}) {{backend}} {{exported_namespace}} "
    }
   ]
  },
  {
   "title": "Incoming / Outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bits", "label": "- out / + in" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_bytes_in_total{frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "IN Front"
    },
    {
     "expr": "sum(rate(haproxy_frontend_bytes_out_total{frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "OUT Front"
    },
    {
     "expr": "sum(rate(haproxy_backend_bytes_in_total{backend=~\"$backend\",pod=~\"$host\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "IN Back"
    },
    {
     "expr": "sum(rate(haproxy_backend_bytes_out_total{backend=~\"$backend\",pod=~\"$host\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "OUT Back"
    }
   ]
  },
  {
   "title": "Rate of Number of connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "- back / + front" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_connections_total{frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(rate(haproxy_backend_connection_errors_total{backend=~\"$backend\",pod=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back errors"
    }
   ]
  },
  {
   "title": "HTTP responses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "- back / + front" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_responses_total{frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Front http response"
    },
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{backend=~\"$backend\",pod=~\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back http response"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "- back / + front" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_frontend_current_sessions{frontend=~\"$frontend\",pod=~\"$host\"}) by (instance)",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(haproxy_backend_current_sessions{backend=~\"$backend\",pod=~\"$host\"}) by (instance)",
     "legendFormat": "Back"
    }
   ]
  },
  {
   "title": "Basic General Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Status",
     "type": "graph",
     "gridPos": { "h": 4, "w": 15, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "- back / + front" }
     ],
     "targets": [
      {
       "expr": "count(haproxy_server_up{pod=~\"$host\"} == 1)",
       "legendFormat": "Server Up"
      },
      {
       "expr": "count(haproxy_backend_up{pod=~\"$host\"} ==1)",
       "legendFormat": "Backend Up"
      }
     ]
    },
    {
     "title": "Started time (Seconds)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 9, "x": 15, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - haproxy_process_start_time_seconds{pod=~\"$host\"}"
      }
     ]
    }
   ]
  },
  { "title": "Throughtput / Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Front - Incoming / Outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bits", "label": "- out / + in" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_frontend_bytes_in_total{frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])*8",
     "legendFormat": "IN {{ frontend }} "
    },
    {
     "expr": "rate(haproxy_frontend_bytes_out_total{frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])*8",
     "legendFormat": "OUT {{ frontend }}"
    }
   ]
  },
  {
   "title": "Back - Incoming / Outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bits", "label": "- out / + in" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_backend_bytes_in_total{backend=~\"$backend\",pod=~\"$host\"}[$__rate_interval])*8",
     "legendFormat": "IN {{ backend }} NS:{{exported_namespace}} Route:{{route}}"
    },
    {
     "expr": "rate(haproxy_backend_bytes_out_total{backend=~\"$backend\",pod=~\"$host\"}[$__rate_interval])*8",
     "legendFormat": "OUT  {{ backend }} NS:{{exported_namespace}} Route:{{route}}"
    }
   ]
  },
  {
   "title": "Front - Connections successful",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "successful" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_frontend_connections_total{frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "Successful {{ frontend }}"
    }
   ]
  },
  {
   "title": "Back - response errors (Rate)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "- error / + attempt" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_backend_response_errors_total{backend=~\"$backend\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "Error {{ backend }} NS: {{exported_namespace}} Route: {{route}}"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Back - Queued requests not assigned to any server",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "requests" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_queue{backend=~\"$backend\",pod=~\"$host\"}",
     "legendFormat": "Queued {{ backend }} {{pod}}"
    }
   ]
  },
  { "title": "Requests / Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Back - HTTP response 200 / Others",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short", "label": "- Others / + 200" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_backend_http_responses_total{code=~\"2xx\",backend=~\"$backend\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "200 {{ backend }} {{exported_namespace}} {{route}}"
    },
    {
     "expr": "rate(haproxy_backend_http_responses_total{code=~\"4xx\",backend=~\"$backend\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "4xx {{ backend }} {{exported_namespace}} {{route}}"
    },
    {
     "expr": "rate(haproxy_backend_http_responses_total{code=~\"5xx\",backend=~\"$backend\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "5xx {{ backend }} {{exported_namespace}} {{route}}"
    },
    {
     "expr": "rate(haproxy_backend_http_responses_total{code=~\"3xx\",backend=~\"$backend\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "3xx {{ backend }} {{exported_namespace}} {{route}}"
    }
   ]
  },
  {
   "title": "Front - HTTP response 200 / Other",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short", "label": "- Others / + 200" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_frontend_http_responses_total{code=~\"2xx\",frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "200 {{ frontend }}"
    },
    {
     "expr": "rate(haproxy_frontend_http_responses_total{code=~\"3xx\",frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "3xx {{ frontend }}"
    },
    {
     "expr": "rate(haproxy_frontend_http_responses_total{code=~\"4xx\",frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "4xx {{ frontend }}"
    },
    {
     "expr": "rate(haproxy_frontend_http_responses_total{code=~\"5xx\",frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "5xx {{ frontend }}"
    }
   ]
  },
  { "title": "Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Back - http average connect latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_http_average_connect_latency_milliseconds{backend=~\"$backend\",pod=~\"$host\"}",
     "legendFormat": "{{ backend }} NS:{{exported_namespace}} Route:{{route}}"
    }
   ]
  },
  { "title": "Responses by HTTP code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Front - HTTP responses code",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short", "label": "responses" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_frontend_http_responses_total{frontend=~\"$frontend\", code=~\"$code\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "{{ code }} {{ frontend }} {{pod}}"
    }
   ]
  },
  {
   "title": "Back - HTTP responses code",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "short", "label": "responses" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_backend_http_responses_total{backend=~\"$backend\", code=~\"$code\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "{{ code }} {{ backend }} NS:{{exported_namespace}} Route:{{route}}"
    }
   ]
  },
  {
   "title": "Server - HTTP responses code",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_server_http_responses_total{code=~\"$code\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "{{ code }} {{ exported_pod }} {{ server }}"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "Back - Maximum observed number of active sessions and limit",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "short", "label": "sessions" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_max_sessions{backend=~\"$backend\",pod=~\"$host\"}",
     "legendFormat": "Max {{ backend }} NS:{{exported_namespace}} Route:{{route}}"
    }
   ]
  },
  {
   "title": "Back - Number of sessions",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 126 },
   "yaxes": [
    { "format": "short", "label": "total" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_sessions{backend=~\"$backend\",pod=~\"$host\"}",
     "legendFormat": "Current active {{ backend }} NS:{{exported_namespace}} Route:{{route}}"
    }
   ]
  },
  {
   "title": "Back - Maximum observed number of sessions per second",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "short", "label": "sessions" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_max_session_rate{backend=~\"$backend\",pod=~\"$host\"}",
     "legendFormat": "Max {{ backend }} NS:{{exported_namespace}} Route:{{route}}"
    }
   ]
  },
  {
   "title": "Front - Maximum observed number of active sessions",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 139 },
   "yaxes": [
    { "format": "short", "label": "sessions" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_max_sessions{frontend=~\"$frontend\",pod=~\"$host\"}",
     "legendFormat": "Max {{ frontend }} {{pod}}"
    }
   ]
  },
  {
   "title": "Front - Number of sessions",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_current_sessions{frontend=~\"$frontend\",pod=~\"$host\"}",
     "legendFormat": "Current active {{ frontend }}"
    }
   ]
  },
  {
   "title": "Front - Maximum observed number of sessions per second",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 152 },
   "yaxes": [
    { "format": "short", "label": "sessions" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_max_session_rate{frontend=~\"$frontend\",pod=~\"$host\"}",
     "legendFormat": "Max {{ frontend }}"
    }
   ]
  },
  { "title": "Cache / Compressor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 165 } },
  {
   "title": "Front - Cache lookups / hits",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_frontend_http_cache_lookups_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Lookups {{ proxy }} "
    },
    {
     "expr": "rate(haproxy_frontend_http_cache_hits_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Hits {{ proxy }} "
    }
   ]
  },
  {
   "title": "Back - Cache lookups / hits",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 166 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_backend_http_cache_lookups_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Lookups {{ proxy }} "
    },
    {
     "expr": "rate(haproxy_backend_http_cache_hits_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Hits {{ proxy }} "
    }
   ]
  },
  {
   "title": "Front - Compressor",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 177 },
   "yaxes": [
    { "format": "bytes", "label": "- emitted / + bypasses + fed" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_frontend_http_comp_bytes_in_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Bytes fed {{ proxy }} "
    },
    {
     "expr": "rate(haproxy_frontend_http_comp_bytes_out_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Bytes emitted {{ proxy }} "
    },
    {
     "expr": "rate(haproxy_frontend_http_comp_bytes_bypassed_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Bytes bypassed  {{ proxy }} "
    }
   ]
  },
  {
   "title": "Back - Compressor",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 177 },
   "yaxes": [
    { "format": "bytes", "label": "- emitted / + bypasses + fed" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_backend_http_comp_bytes_in_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Bytes fed {{ proxy }} "
    },
    {
     "expr": "rate(haproxy_backend_http_comp_bytes_out_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Bytes emitted {{ proxy }} "
    },
    {
     "expr": "rate(haproxy_backend_http_comp_bytes_bypassed_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Bytes bypassed  {{ proxy }} "
    }
   ]
  },
  {
   "title": "Front - Responses compressed",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 188 },
   "yaxes": [
    { "format": "short", "label": "responses" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_frontend_http_comp_responses_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{ proxy }} "
    }
   ]
  },
  {
   "title": "Back - Responses compressed",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 188 },
   "yaxes": [
    { "format": "short", "label": "responses" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_backend_http_comp_responses_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{ proxy }} "
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 199 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Status",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_frontend_status{proxy=~\"$frontend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Status",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_status{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Internal errors",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_frontend_internal_errors_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Internal errors",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_backend_internal_errors_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Active servers",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "- backup / + active" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_active_servers{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Backup servers",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "- backup / + active" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_backup_servers{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Throughtput  / Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Incoming / Outgoing bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bits", "label": "- out / + in" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_bytes_in_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "IN {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_bytes_out_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "OUT {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_used_connections_current{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "In use {{ proxy }} / {{ server }}{{ proxy }}"
      },
      {
       "expr": "rate(haproxy_server_idle_connections_current{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Estimated {{ proxy }} / {{ server }}{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Connections attempts / error",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short", "label": "- error / + attempts" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_connection_attempts_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Attempts {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_connection_errors_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of connections reuses",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short", "label": "reuses" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_connection_reuses_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Reuses {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Idle connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_idle_connections_current{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Available idle connections {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_idle_connections_limit{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Limit available idle connections {{ proxy }} / {{ server }}{{ proxy }}"
      },
      {
       "expr": "rate(haproxy_server_safe_idle_connections_current{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Number of safe idle connections {{ proxy }} / {{ server }}{{ proxy }}"
      },
      {
       "expr": "rate(haproxy_server_unsafe_idle_connections_current{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Number of unsafe idle connections {{ proxy }} / {{ server }}{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Requests / Responses / Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 201 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - HTTP responses denied",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "denied" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_responses_denied_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Error / Redispatch / Retry",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "- error / + redispatch + retry" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_redispatch_warnings_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Redispatch {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_retry_warnings_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Retry {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_response_errors_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Queued requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short", "label": "requests" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_current_queue{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Current {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max  queued requests and limit",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short", "label": "requests" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_max_queue{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "Max {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_queue_limit{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 202 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Average connection time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_connect_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max connection time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_max_connect_time_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average response time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_response_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max response time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_max_response_time_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average total time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_total_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max total time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_max_total_time_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average queue time for last 1024 successful connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_queue_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max queue time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_max_queue_time_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 203 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Number of active sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 174 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_sessions_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_limit_sessions{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Failed header rewriting warnings",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 182 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_failed_header_rewriting_total{proxy=~\"$frontend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} /  {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of sessions per second and limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 191 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_max_session_rate{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "Rate {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_limit_session_rate{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Health and Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 204 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Service weight",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "none", "label": "weight" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_weight{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Users weight",
     "type": "graph",
     "description": "Server's user weight, or sum of active servers' user weights for a backend",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none", "label": "weight" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_uweight{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - UP->DOWN transitions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "none", "label": "transitions" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_check_up_down_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Checks failures",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "none", "label": "failures" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_check_failures_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Checks duration",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_check_duration_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server -Throttle percentage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_current_throttle{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of seconds since last session assigned to server/backend",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_last_session_seconds{proxy=~\"$backend\", server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 205 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_status{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Internal errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_internal_errors_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Failed DNS resolutions",
     "type": "graph",
     "description": "Number of failed DNS resolutions in current worker process since started",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_process_failed_resolutions{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Failed"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Connections / Sessions / Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 206 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - Sessions over last second",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_current_session_rate{instance=\"$host\"}",
       "legendFormat": "Current number of sessions per second over last elapsed second"
      },
      {
       "expr": "haproxy_process_limit_session_rate{instance=\"$host\"}",
       "legendFormat": "Configured maximum number of sessions per second"
      }
     ]
    },
    {
     "title": "Process - Total sessions / requests",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_process_connections_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total number of created sessions"
      },
      {
       "expr": "rate(haproxy_process_requests_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total number of requests (TCP or HTTP)"
      }
     ]
    },
    {
     "title": "Process - Connections over last second",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_current_connection_rate{instance=\"$host\"}",
       "legendFormat": "Current number of connections per second over last elapsed second"
      },
      {
       "expr": "haproxy_process_limit_connection_rate{instance=\"$host\"}",
       "legendFormat": "Configured maximum number of connections per second."
      }
     ]
    },
    {
     "title": "Process - Max connections",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_max_connections{instance=\"$host\"}",
       "legendFormat": "Maximum number of concurrent connections"
      },
      {
       "expr": "haproxy_process_hard_max_connections{instance=\"$host\"}",
       "legendFormat": "Initial Maximum number of concurrent connections"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Compression",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 207 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - Compression memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_current_zlib_memory{instance=\"$host\"}",
       "legendFormat": "Current memory used for zlib in bytes"
      },
      {
       "expr": "haproxy_process_max_zlib_memory{instance=\"$host\"}",
       "legendFormat": "Configured maximum amount of memory for zlib in bytes"
      }
     ]
    },
    {
     "title": "Process - Compression",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "- before / + after" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_process_http_comp_bytes_in_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Number of bytes per second over last elapsed second, before http compression"
      },
      {
       "expr": "rate(haproxy_process_http_comp_bytes_out_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Number of bytes per second over last elapsed second, after http compression"
      },
      {
       "expr": "haproxy_process_limit_http_comp{instance=\"$host\"}",
       "legendFormat": "Configured maximum input compression rate in bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Process SSL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 208 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - SSL cache",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "- misses / + lookups" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_process_ssl_cache_lookups_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total number of SSL session cache lookups"
      },
      {
       "expr": "rate(haproxy_process_ssl_cache_misses_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total number of SSL session cache misses"
      }
     ]
    },
    {
     "title": "Process - SSL key rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "- backend / + frontend" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_current_frontend_ssl_key_rate{instance=\"$host\"}",
       "legendFormat": "Current frontend SSL Key computation per second over last elapsed second"
      },
      {
       "expr": "haproxy_process_current_backend_ssl_key_rate{instance=\"$host\"}",
       "legendFormat": "Current backend SSL Key computation per second over last elapsed second"
      }
     ]
    },
    {
     "title": "Process - SSL rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_current_ssl_rate{instance=\"$host\"}",
       "legendFormat": "Current number of SSL sessions per second over last elapsed second"
      },
      {
       "expr": "haproxy_process_limit_ssl_rate{instance=\"$host\"}",
       "legendFormat": "Configured maximum number of SSL sessions per second"
      }
     ]
    },
    {
     "title": "Process - SSL connections",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_current_ssl_connections{instance=\"$host\"}",
       "legendFormat": "Current number of opened SSL connections"
      },
      {
       "expr": "haproxy_process_max_ssl_connections{instance=\"$host\"}",
       "legendFormat": "Configured maximum number of concurrent SSL connections"
      }
     ]
    },
    {
     "title": "Process - SSL reuse ratio",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "percent", "label": "ratio" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_frontend_ssl_reuse{instance=\"$host\"}",
       "legendFormat": "SSL session reuse ratio (percent)"
      }
     ]
    }
   ]
  },
  { "title": "Process Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 209 } },
  {
   "title": "Process - Memory",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 210 },
   "yaxes": [
    { "format": "bytes", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "haproxy_process_virtual_memory_bytes{pod=~\"$host\"}",
     "legendFormat": "Virtual memory  {{pod}}"
    },
    {
     "expr": "haproxy_process_resident_memory_bytes{pod=~\"$host\"}",
     "legendFormat": "Resident memory {{pod}}"
    }
   ]
  },
  {
   "title": "Process - Total cpu time",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 210 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_process_cpu_seconds_total{pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}