{
 "title": "HAProxy Dashboard for OpenShift 4 Router",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "host", "label": "Host", "query": { "query": "label_values(haproxy_up{},pod)" } },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_bytes_in_total{pod=~\"$host\"},backend)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_bytes_in_total{pod=~\"$host\"},frontend)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_bytes_in_total{pod=~\"$host\"}, exported_pod)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{}, code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Basic General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All HTTP responses rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "- back / + front" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_responses_total{frontend=~\"$frontend\",code=~\"$code\",pod=~\"$host\"}[$__rate_interval])) by (code)",
     "legendFormat": "Frontend: [ {{code}} ] ({{pod}}) {{frontend}} "
    },
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{backend=~\"$backend\",code=~\"$code\",pod=~\"$host\"}[$__rate_interval])) by (code)",
     "legendFormat": "Backend: [ {{code}} ] ({{pod}}) {{backend}} {{exported_namespace}} "
    }
   ]
  },
  {
   "title": "Incoming / Outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bits", "label": "- out / + in" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_bytes_in_total{frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "IN Front"
    },
    {
     "expr": "sum(rate(haproxy_frontend_bytes_out_total{frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "OUT Front"
    },
    {
     "expr": "sum(rate(haproxy_backend_bytes_in_total{backend=~\"$backend\",pod=~\"$host\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "IN Back"
    },
    {
     "expr": "sum(rate(haproxy_backend_bytes_out_total{backend=~\"$backend\",pod=~\"$host\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "OUT Back"
    }
   ]
  },
  {
   "title": "Rate of Number of connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "- back / + front" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_connections_total{frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(rate(haproxy_backend_connection_errors_total{backend=~\"$backend\",pod=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back errors"
    }
   ]
  },
  {
   "title": "HTTP responses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "- back / + front" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_responses_total{frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Front http response"
    },
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{backend=~\"$backend\",pod=~\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back http response"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "- back / + front" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_frontend_current_sessions{frontend=~\"$frontend\",pod=~\"$host\"}) by (instance)",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(haproxy_backend_current_sessions{backend=~\"$backend\",pod=~\"$host\"}) by (instance)",
     "legendFormat": "Back"
    }
   ]
  },
  { "title": "Basic General Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "All Status",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "- back / + front" }
   ],
   "targets": [
    {
     "expr": "count(haproxy_server_up{pod=~\"$host\"} == 1)",
     "legendFormat": "Server Up"
    },
    {
     "expr": "count(haproxy_backend_up{pod=~\"$host\"} ==1)",
     "legendFormat": "Backend Up"
    }
   ]
  },
  { "title": "Throughtput / Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Front - Incoming / Outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bits", "label": "- out / + in" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_frontend_bytes_in_total{frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])*8",
     "legendFormat": "IN {{ frontend }} "
    },
    {
     "expr": "rate(haproxy_frontend_bytes_out_total{frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])*8",
     "legendFormat": "OUT {{ frontend }}"
    }
   ]
  },
  {
   "title": "Back - Incoming / Outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "bits", "label": "- out / + in" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_backend_bytes_in_total{backend=~\"$backend\",pod=~\"$host\"}[$__rate_interval])*8",
     "legendFormat": "IN {{ backend }} NS:{{exported_namespace}} Route:{{route}}"
    },
    {
     "expr": "rate(haproxy_backend_bytes_out_total{backend=~\"$backend\",pod=~\"$host\"}[$__rate_interval])*8",
     "legendFormat": "OUT  {{ backend }} NS:{{exported_namespace}} Route:{{route}}"
    }
   ]
  },
  {
   "title": "Front - Connections successful",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short", "label": "successful" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_frontend_connections_total{frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "Successful {{ frontend }}"
    }
   ]
  },
  {
   "title": "Back - response errors (Rate)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short", "label": "- error / + attempt" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_backend_response_errors_total{backend=~\"$backend\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "Error {{ backend }} NS: {{exported_namespace}} Route: {{route}}"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Back - Queued requests not assigned to any server",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short", "label": "requests" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_queue{backend=~\"$backend\",pod=~\"$host\"}",
     "legendFormat": "Queued {{ backend }} {{pod}}"
    }
   ]
  },
  { "title": "Requests / Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Back - HTTP response 200 / Others",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short", "label": "- Others / + 200" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_backend_http_responses_total{code=~\"2xx\",backend=~\"$backend\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "200 {{ backend }} {{exported_namespace}} {{route}}"
    },
    {
     "expr": "rate(haproxy_backend_http_responses_total{code=~\"4xx\",backend=~\"$backend\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "4xx {{ backend }} {{exported_namespace}} {{route}}"
    },
    {
     "expr": "rate(haproxy_backend_http_responses_total{code=~\"5xx\",backend=~\"$backend\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "5xx {{ backend }} {{exported_namespace}} {{route}}"
    },
    {
     "expr": "rate(haproxy_backend_http_responses_total{code=~\"3xx\",backend=~\"$backend\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "3xx {{ backend }} {{exported_namespace}} {{route}}"
    }
   ]
  },
  {
   "title": "Front - HTTP response 200 / Other",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short", "label": "- Others / + 200" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_frontend_http_responses_total{code=~\"2xx\",frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "200 {{ frontend }}"
    },
    {
     "expr": "rate(haproxy_frontend_http_responses_total{code=~\"3xx\",frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "3xx {{ frontend }}"
    },
    {
     "expr": "rate(haproxy_frontend_http_responses_total{code=~\"4xx\",frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "4xx {{ frontend }}"
    },
    {
     "expr": "rate(haproxy_frontend_http_responses_total{code=~\"5xx\",frontend=~\"$frontend\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "5xx {{ frontend }}"
    }
   ]
  },
  { "title": "Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Back - http average connect latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_http_average_connect_latency_milliseconds{backend=~\"$backend\",pod=~\"$host\"}",
     "legendFormat": "{{ backend }} NS:{{exported_namespace}} Route:{{route}}"
    }
   ]
  },
  { "title": "Responses by HTTP code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Front - HTTP responses code",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short", "label": "responses" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_frontend_http_responses_total{frontend=~\"$frontend\", code=~\"$code\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "{{ code }} {{ frontend }} {{pod}}"
    }
   ]
  },
  {
   "title": "Back - HTTP responses code",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "short", "label": "responses" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_backend_http_responses_total{backend=~\"$backend\", code=~\"$code\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "{{ code }} {{ backend }} NS:{{exported_namespace}} Route:{{route}}"
    }
   ]
  },
  {
   "title": "Server - HTTP responses code",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_server_http_responses_total{code=~\"$code\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "{{ code }} {{ exported_pod }} {{ server }}"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 } },
  {
   "title": "Back - Maximum observed number of active sessions and limit",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "short", "label": "sessions" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_max_sessions{backend=~\"$backend\",pod=~\"$host\"}",
     "legendFormat": "Max {{ backend }} NS:{{exported_namespace}} Route:{{route}}"
    }
   ]
  },
  {
   "title": "Back - Number of sessions",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 130 },
   "yaxes": [
    { "format": "short", "label": "total" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_sessions{backend=~\"$backend\",pod=~\"$host\"}",
     "legendFormat": "Current active {{ backend }} NS:{{exported_namespace}} Route:{{route}}"
    }
   ]
  },
  {
   "title": "Back - Maximum observed number of sessions per second",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "short", "label": "sessions" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_max_session_rate{backend=~\"$backend\",pod=~\"$host\"}",
     "legendFormat": "Max {{ backend }} NS:{{exported_namespace}} Route:{{route}}"
    }
   ]
  },
  {
   "title": "Front - Maximum observed number of active sessions",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 143 },
   "yaxes": [
    { "format": "short", "label": "sessions" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_max_sessions{frontend=~\"$frontend\",pod=~\"$host\"}",
     "legendFormat": "Max {{ frontend }} {{pod}}"
    }
   ]
  },
  {
   "title": "Front - Number of sessions",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 156 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_current_sessions{frontend=~\"$frontend\",pod=~\"$host\"}",
     "legendFormat": "Current active {{ frontend }}"
    }
   ]
  },
  {
   "title": "Front - Maximum observed number of sessions per second",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 156 },
   "yaxes": [
    { "format": "short", "label": "sessions" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_max_session_rate{frontend=~\"$frontend\",pod=~\"$host\"}",
     "legendFormat": "Max {{ frontend }}"
    }
   ]
  },
  {
   "title": "By server - Throughtput  / Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 }
  },
  {
   "title": "Server - Incoming / Outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 170 },
   "yaxes": [
    { "format": "bits", "label": "- out / + in" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_server_bytes_in_total{exported_pod=~\"$server\",pod=~\"$host\"}[$__rate_interval])*8",
     "legendFormat": "IN {{ proxy }} / {{ server }}"
    },
    {
     "expr": "rate(haproxy_server_bytes_out_total{exported_pod=~\"$server\",pod=~\"$host\"}[$__rate_interval])*8",
     "legendFormat": "OUT {{ proxy }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 178 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_server_connections_total{exported_pod=~\"$server\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "In use {{ proxy }} / {{ server }}{{ proxy }}"
    }
   ]
  },
  { "title": "By server - Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 187 } },
  {
   "title": "Server - Number of active sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 188 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_current_sessions{exported_pod=~\"$server\",pod=~\"$host\"}",
     "legendFormat": "Current {{ proxy }} / {{ server }}"
    },
    {
     "expr": "rate(haproxy_server_max_sessions{exported_pod=~\"$server\",pod=~\"$host\"}[$__rate_interval])",
     "legendFormat": "Max {{ proxy }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Number of sessions per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 196 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_max_session_rate{exported_pod=~\"$server\",pod=~\"$host\"}",
     "legendFormat": "Rate {{ exported_pod }}"
    }
   ]
  },
  {
   "title": "Process Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 204 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - Memory",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 143 },
     "yaxes": [
      { "format": "bytes", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_virtual_memory_bytes{pod=~\"$host\"}",
       "legendFormat": "Virtual memory  {{pod}}"
      },
      {
       "expr": "haproxy_process_resident_memory_bytes{pod=~\"$host\"}",
       "legendFormat": "Resident memory {{pod}}"
      }
     ]
    },
    {
     "title": "Process - Total cpu time",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 143 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_process_cpu_seconds_total{pod=~\"$host\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}